apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: psa-secure-namespace
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: git@github.com:shackdan/secure-cluster.git
    path: manifests/psa
  destination:
    server: https://kubernetes.default.svc
    namespace: secure-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
